### PR TITLE
Fixed feedback comments

### LINKED ISSUE #13: Fix feeback comments

### PR DESCRIPTION
**Pull request by vijay2136**
fixes #13 
- Moved constants to closest scope

### CODE REVIEW

File: app/javascript/src/components/Authentication/Signup.jsx [hunk 1]
```diff
@@ -6,8 +6,9 @@ import { Input } from "neetoui/formik";
 import PropTypes from "prop-types";
 
 import authenticationApi from "apis/authentication";
-import formInitialValues from "constants/formInitialValues";
-import formValidationSchemas from "constants/formValidationSchemas";
+
+import formInitialValues from "./constants/formInitialValues";
+import formValidationSchemas from "./constants/formValidationSchemas";
```
Comment (yedhink) [inline app/javascript/src/components/Authentication/Signup.jsx]: Keep these are constants within a single `constants.js` file. Currently there is not enough content so as to split them out into separate files.

**Review by yedhink — CHANGES_REQUESTED** [review]
@vijay2136 

You can work on this in your free time or in weekend or when you haven't been assigned anything else. First priority is neeto work.
